export const START_QUIZ = 'START_QUIZ';
export const ATTEMPT_QUESTION = 'ATTEMPT_QUESTION';
export const LOAD_QUESTIONS = 'LOAD_QUESTIONS';
export const LOAD_QUESTIONS_FAILED = 'LOAD_QUESTIONS_FAILED';
export const STORE_QUESTIONS = 'STORE_QUESTIONS';

export const SUBMIT_QUIZ = 'SUBMIT_QUIZ';
export const STORE_SCORE = 'STORE_SCORE';
export const SUBMIT_QUIZ_FAILED = 'SUBMIT_QUIZ_FAILED';