export const LOGIN_FORM_UPDATED = 'LOGIN_FORM_UPDATED';
export const LOGIN_FORM_COMPLETED = 'LOGIN_FORM_COMPLETED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const STORE_SESSION = 'STORE_SESSION'